#!/usr/bin/env bash
set -euo pipefail
VERSION=$(node -p "require('./package.json').version")
cat > src/version.ts <<EOF
// Auto-generated by scripts/generate-version.sh — do not edit.
export const SDK_VERSION = '${VERSION}';
export const VERSION = SDK_VERSION;

declare global {
  const __LILY_SDK_VERSION__: string;
}
EOF
