import fs from 'node:fs';

const pkg = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
const content = `// Auto-generated by scripts/generate-version.mjs — do not edit.
export const SDK_VERSION = '${pkg.version}';
export const VERSION = SDK_VERSION;

declare global {
  const __LILY_SDK_VERSION__: string;
}
`;

fs.writeFileSync('src/version.ts', content);
